name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: my-image-name

    steps:
    - uses: actions/checkout@v2
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.IMAGE_NAME }}

    - name: Container image scan
      uses: Azure/container-scan@v0.1
      with:
        image-name: ${{ env.IMAGE_NAME }}
        severity-threshold: WARN
